# Generated by Django 3.2.5 on 2021-07-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bookstore', '0006_rename_user_book_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
