# Generated by Django 3.2.5 on 2021-07-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_bookstore', '0009_alter_book_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='added_by',
            new_name='username',
        ),
    ]
