# Generated by Django 3.2.5 on 2021-07-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_bookstore', '0010_rename_added_by_book_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='username',
            new_name='added_by',
        ),
    ]
